### ISSUE TITLE
Doesn't work with Android build react-native@0.60+

### ISSUE THREAD

**Issue by oleksandr-dziuban** [gre/react-native-view-shot#229]
### feature request

Add support for AndroidX (react-native@0.60+)

### bug report Application cannot be built for Android platform with latest react-native@0.60+. See following errors when trying to assemble dev build:
```bash
oid.support.annotation does not exist
import android.support.annotation.IntDef;
                                 ^
/Users/sanogtx/WebstormProjects/EPAM_Projects/ELAT-DEV/mobile-ui-configure/node_modules/react-native-view-shot/android/src/main/java/fr/greweb/reactnativeviewshot/ViewShot.java:12: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
/Users/sanogtx/WebstormProjects/EPAM_Projects/ELAT-DEV/mobile-ui-configure/node_modules/react-native-view-shot/android/src/main/java/fr/greweb/reactnativeviewshot/ViewShot.java:13: error: package android.support.annotation does not exist
import android.support.annotation.StringDef;
                                 ^
/Users/sanogtx/WebstormProjects/EPAM_Projects/ELAT-DEV/mobile-ui-configure/node_modules/react-native-view-shot/android/src/main/java/fr/greweb/reactnativeviewshot/ViewShot.java:70: error: cannot find symbol
    @IntDef({Formats.JPEG, Formats.PNG, Formats.WEBP, Formats.RAW})
     ^
  symbol:   class IntDef
  location: class ViewShot
/Users/sanogtx/WebstormProjects/EPAM_Projects/ELAT-DEV/mobile-ui-configure/node_modules/react-native-view-shot/android/src/main/java/fr/greweb/reactnativeviewshot/ViewShot.java:87: error: cannot find symbol
    @StringDef({Results.BASE_64, Results.DATA_URI, Results.TEMP_FILE, Results.ZIP_BASE_64})
     ^
  symbol:   class StringDef
  location: class ViewShot
/Users/sanogtx/WebstormProjects/EPAM_Projects/ELAT-DEV/mobile-ui-configure/node_modules/react-native-view-shot/android/src/main/java/fr/greweb/reactnativeviewshot/RNViewShotModule.java:8: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
/Users/sanogtx/WebstormProjects/EPAM_Projects/ELAT-DEV/mobile-ui-configure/node_modules/react-native-view-shot/android/src/main/java/fr/greweb/reactnativeviewshot/DebugViews.java:8: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
/Users/sanogtx/WebstormProjects/EPAM_Projects/ELAT-DEV/mobile-ui-configure/node_modules/react-native-view-shot/android/src/main/java/fr/greweb/reactnativeviewshot/DebugViews.java:9: error: package android.support.v4.util does not exist
import android.support.v4.util.Pair;
                              ^
/Users/sanogtx/WebstormProjects/EPAM_Projects/ELAT-DEV/mobile-ui-configure/node_modules/react-native-view-shot/android/src/main/java/fr/greweb/reactnativeviewshot/ViewShot.java:202: error: cannot find symbol
    private void saveToTempFileOnDevice(@NonNull final View view) throws IOException {
                                         ^
  symbol:   class NonNull
  location: class ViewShot
/Users/sanogtx/WebstormProjects/EPAM_Projects/ELAT-DEV/mobile-ui-configure/node_modules/react-native-view-shot/android/src/main/java/fr/greweb/reactnativeviewshot/ViewShot.java:209: error: cannot find symbol
    private void saveToRawFileOnDevice(@NonNull final View view) throws IOException {
                                        ^
  symbol:   class NonNull
  location: class ViewShot
/Users/sanogtx/WebstormProjects/EPAM_Projects/ELAT-DEV/mobile-ui-configure/node_modules/react-native-view-shot/android/src/main/java/fr/greweb/reactnativeviewshot/ViewShot.java:228: error: cannot find symbol
    private void saveToDataUriString(@NonNull final View view) throws IOException {
                                      ^
  symbol:   class NonNull
  location: class ViewShot
/Users/sanogtx/WebstormProjects/EPAM_Projects/ELAT-DEV/mobile-ui-configure/node_modules/react-native-view-shot/android/src/main/java/fr/greweb/reactnativeviewshot/ViewShot.java:243: error: cannot find symbol
    private void saveToBase64String(@NonNull final View view) throws IOException {
                                     ^
  symbol:   class NonNull
  location: class ViewShot
/Users/sanogtx/WebstormProjects/EPAM_Projects/ELAT-DEV/mobile-ui-configure/node_modules/react-native-view-shot/android/src/main/java/fr/greweb/reactnativeviewshot/ViewShot.java:278: error: cannot find symbol
    private List<View> getAllChildren(@NonNull final View v) {
                                       ^
  symbol:   class NonNull
  location: class ViewShot
/Users/sanogtx/WebstormProjects/EPAM_Projects/ELAT-DEV/mobile-ui-configure/node_modules/react-native-view-shot/android/src/main/java/fr/greweb/reactnativeviewshot/ViewShot.java:277: error: cannot find symbol
    @NonNull
     ^
  symbol:   class NonNull
  location: class ViewShot
/Users/sanogtx/WebstormProjects/EPAM_Projects/ELAT-DEV/mobile-ui-configure/node_modules/react-native-view-shot/android/src/main/java/fr/greweb/reactnativeviewshot/ViewShot.java:302: error: cannot find symbol
    private Point captureView(@NonNull final View view, @NonNull final OutputStream os) throws IOException {
                               ^
  symbol:   class NonNull
  location: class ViewShot
/Users/sanogtx/WebstormProjects/EPAM_Projects/ELAT-DEV/mobile-ui-configure/node_modules/react-native-view-shot/android/src/main/java/fr/greweb/reactnativeviewshot/ViewShot.java:302: error: cannot find symbol
    private Point captureView(@NonNull final View view, @NonNull final OutputStream os) throws IOException {
                                                         ^
  symbol:   class NonNull
  location: class ViewShot
/Users/sanogtx/WebstormProjects/EPAM_Projects/ELAT-DEV/mobile-ui-configure/node_modules/react-native-view-shot/android/src/main/java/fr/greweb/reactnativeviewshot/ViewShot.java:318: error: cannot find symbol
    private Point captureViewImpl(@NonNull final View view, @NonNull final OutputStream os) {
                                   ^
  symbol:   class NonNull
  location: class ViewShot
/Users/sanogtx/WebstormProjects/EPAM_Projects/ELAT-DEV/mobile-ui-configure/node_modules/react-native-view-shot/android/src/main/java/fr/greweb/reactnativeviewshot/ViewShot.java:318: error: cannot find symbol
    private Point captureViewImpl(@NonNull final View view, @NonNull final OutputStream os) {
                                                             ^
  symbol:   class NonNull
  location: class ViewShot
/Users/sanogtx/WebstormProjects/EPAM_Projects/ELAT-DEV/mobile-ui-configure/node_modules/react-native-view-shot/android/src/main/java/fr/greweb/reactnativeviewshot/ViewShot.java:405: error: cannot find symbol
    private Matrix applyTransformations(final Canvas c, @NonNull final View root, @NonNull final View child) {
                                                         ^
  symbol:   class NonNull
  location: class ViewShot
/Users/sanogtx/WebstormProjects/EPAM_Projects/ELAT-DEV/mobile-ui-configure/node_modules/react-native-view-shot/android/src/main/java/fr/greweb/reactnativeviewshot/ViewShot.java:405: error: cannot find symbol
    private Matrix applyTransformations(final Canvas c, @NonNull final View root, @NonNull final View child) {
                                                                                   ^
  symbol:   class NonNull
  location: class ViewShot
/Users/sanogtx/WebstormProjects/EPAM_Projects/ELAT-DEV/mobile-ui-configure/node_modules/react-native-view-shot/android/src/main/java/fr/greweb/reactnativeviewshot/ViewShot.java:403: error: cannot find symbol
    @NonNull
     ^
  symbol:   class NonNull
  location: class ViewShot
/Users/sanogtx/WebstormProjects/EPAM_Projects/ELAT-DEV/mobile-ui-configure/node_modules/react-native-view-shot/android/src/main/java/fr/greweb/reactnativeviewshot/ViewShot.java:458: error: cannot find symbol
    private static int proposeSize(@NonNull final View view) {
                                    ^
  symbol:   class NonNull
  location: class ViewShot
/Users/sanogtx/WebstormProjects/EPAM_Projects/ELAT-DEV/mobile-ui-configure/node_modules/react-native-view-shot/android/src/main/java/fr/greweb/reactnativeviewshot/ViewShot.java:468: error: cannot find symbol
    private static void recycleBitmap(@NonNull final Bitmap bitmap) {
                                       ^
  symbol:   class NonNull
  location: class ViewShot
/Users/sanogtx/WebstormProjects/EPAM_Projects/ELAT-DEV/mobile-ui-configure/node_modules/react-native-view-shot/android/src/main/java/fr/greweb/reactnativeviewshot/ViewShot.java:477: error: cannot find symbol
    @NonNull
     ^
  symbol:   class NonNull
  location: class ViewShot
/Users/sanogtx/WebstormProjects/EPAM_Projects/ELAT-DEV/mobile-ui-configure/node_modules/react-native-view-shot/android/src/main/java/fr/greweb/reactnativeviewshot/ViewShot.java:496: error: cannot find symbol
    @NonNull
     ^
  symbol:   class NonNull
  location: class ViewShot
/Users/sanogtx/WebstormProjects/EPAM_Projects/ELAT-DEV/mobile-ui-configure/node_modules/react-native-view-shot/android/src/main/java/fr/greweb/reactnativeviewshot/ViewShot.java:521: error: cannot find symbol
        public ReusableByteArrayOutputStream(@NonNull final byte[] buffer) {
                                              ^
  symbol:   class NonNull
  location: class ReusableByteArrayOutputStream
/Users/sanogtx/WebstormProjects/EPAM_Projects/ELAT-DEV/mobile-ui-configure/node_modules/react-native-view-shot/android/src/main/java/fr/greweb/reactnativeviewshot/ViewShot.java:534: error: cannot find symbol
        @NonNull
         ^
  symbol:   class NonNull
  location: class ReusableByteArrayOutputStream
/Users/sanogtx/WebstormProjects/EPAM_Projects/ELAT-DEV/mobile-ui-configure/node_modules/react-native-view-shot/android/src/main/java/fr/greweb/reactnativeviewshot/RNViewShotModule.java:166: error: cannot find symbol
    private File createTempFile(@NonNull final Context context, @NonNull final String ext) throws IOException {
                                 ^
  symbol:   class NonNull
  location: class RNViewShotModule
/Users/sanogtx/WebstormProjects/EPAM_Projects/ELAT-DEV/mobile-ui-configure/node_modules/react-native-view-shot/android/src/main/java/fr/greweb/reactnativeviewshot/RNViewShotModule.java:166: error: cannot find symbol
    private File createTempFile(@NonNull final Context context, @NonNull final String ext) throws IOException {
                                                                 ^
  symbol:   class NonNull
  location: class RNViewShotModule
/Users/sanogtx/WebstormProjects/EPAM_Projects/ELAT-DEV/mobile-ui-configure/node_modules/react-native-view-shot/android/src/main/java/fr/greweb/reactnativeviewshot/RNViewShotModule.java:165: error: cannot find symbol
    @NonNull
     ^
  symbol:   class NonNull
  location: class RNViewShotModule
/Users/sanogtx/WebstormProjects/EPAM_Projects/ELAT-DEV/mobile-ui-configure/node_modules/react-native-view-shot/android/src/main/java/fr/greweb/reactnativeviewshot/RNViewShotModule.java:148: error: cannot find symbol
        private void cleanDirectory(@NonNull final File directory) {
                                     ^
  symbol:   class NonNull
  location: class CleanTask
/Users/sanogtx/WebstormProjects/EPAM_Projects/ELAT-DEV/mobile-ui-configure/node_modules/react-native-view-shot/android/src/main/java/fr/greweb/reactnativeviewshot/DebugViews.java:44: error: cannot find symbol
    public static int longDebug(@NonNull final String tag, @NonNull final String message) {
                                 ^
  symbol:   class NonNull
  location: class DebugViews
/Users/sanogtx/WebstormProjects/EPAM_Projects/ELAT-DEV/mobile-ui-configure/node_modules/react-native-view-shot/android/src/main/java/fr/greweb/reactnativeviewshot/DebugViews.java:44: error: cannot find symbol
    public static int longDebug(@NonNull final String tag, @NonNull final String message) {
                                                            ^
  symbol:   class NonNull
  location: class DebugViews
/Users/sanogtx/WebstormProjects/EPAM_Projects/ELAT-DEV/mobile-ui-configure/node_modules/react-native-view-shot/android/src/main/java/fr/greweb/reactnativeviewshot/DebugViews.java:67: error: cannot find symbol
    public static String logViewHierarchy(@NonNull final Activity activity) {
                                           ^
  symbol:   class NonNull
  location: class DebugViews
/Users/sanogtx/WebstormProjects/EPAM_Projects/ELAT-DEV/mobile-ui-configure/node_modules/react-native-view-shot/android/src/main/java/fr/greweb/reactnativeviewshot/DebugViews.java:66: error: cannot find symbol
    @NonNull
     ^
  symbol:   class NonNull
  location: class DebugViews
/Users/sanogtx/WebstormProjects/EPAM_Projects/ELAT-DEV/mobile-ui-configure/node_modules/react-native-view-shot/android/src/main/java/fr/greweb/reactnativeviewshot/DebugViews.java:80: error: cannot find symbol
    private static String logViewHierarchy(@NonNull final View root) {
                                            ^
  symbol:   class NonNull
  location: class DebugViews
/Users/sanogtx/WebstormProjects/EPAM_Projects/ELAT-DEV/mobile-ui-configure/node_modules/react-native-view-shot/android/src/main/java/fr/greweb/reactnativeviewshot/DebugViews.java:79: error: cannot find symbol
    @NonNull
     ^
  symbol:   class NonNull
  location: class DebugViews
/Users/sanogtx/WebstormProjects/EPAM_Projects/ELAT-DEV/mobile-ui-configure/node_modules/react-native-view-shot/android/src/main/java/fr/greweb/reactnativeviewshot/DebugViews.java:112: error: cannot find symbol
    private static String dumpProperties(@NonNull final Resources r, @NonNull final View v) {
                                          ^
  symbol:   class NonNull
  location: class DebugViews
/Users/sanogtx/WebstormProjects/EPAM_Projects/ELAT-DEV/mobile-ui-configure/node_modules/react-native-view-shot/android/src/main/java/fr/greweb/reactnativeviewshot/DebugViews.java:112: error: cannot find symbol
    private static String dumpProperties(@NonNull final Resources r, @NonNull final View v) {
                                                                      ^
  symbol:   class NonNull
  location: class DebugViews
/Users/sanogtx/WebstormProjects/EPAM_Projects/ELAT-DEV/mobile-ui-configure/node_modules/react-native-view-shot/android/src/main/java/fr/greweb/reactnativeviewshot/DebugViews.java:111: error: cannot find symbol
    @NonNull
     ^
  symbol:   class NonNull
  location: class DebugViews
/Users/sanogtx/WebstormProjects/EPAM_Projects/ELAT-DEV/mobile-ui-configure/node_modules/react-native-view-shot/android/src/main/java/fr/greweb/reactnativeviewshot/DebugViews.java:214: error: cannot find symbol
    private static String resolveIdToName(@Nullable final Resources r, @NonNull final View v) {
                                                                        ^
  symbol:   class NonNull
  location: class DebugViews
/Users/sanogtx/WebstormProjects/EPAM_Projects/ELAT-DEV/mobile-ui-configure/node_modules/react-native-view-shot/android/src/main/java/fr/greweb/reactnativeviewshot/DebugViews.java:213: error: cannot find symbol
    @NonNull
     ^
  symbol:   class NonNull
  location: class DebugViews
/Users/sanogtx/WebstormProjects/EPAM_Projects/ELAT-DEV/mobile-ui-configure/node_modules/react-native-view-shot/android/src/main/java/fr/greweb/reactnativeviewshot/DebugViews.java:83: error: cannot find symbol
        final Stack<Pair<String, View>> stack = new Stack<>();
                    ^
  symbol:   class Pair
  location: class DebugViews
/Users/sanogtx/WebstormProjects/EPAM_Projects/ELAT-DEV/mobile-ui-configure/node_modules/react-native-view-shot/android/src/main/java/fr/greweb/reactnativeviewshot/DebugViews.java:84: error: cannot find symbol
        stack.push(Pair.create("", root));
                   ^
  symbol:   variable Pair
  location: class DebugViews
/Users/sanogtx/WebstormProjects/EPAM_Projects/ELAT-DEV/mobile-ui-configure/node_modules/react-native-view-shot/android/src/main/java/fr/greweb/reactnativeviewshot/DebugViews.java:87: error: cannot find symbol
            @NonNull final Pair<String, View> p = stack.pop();
                           ^
  symbol:   class Pair
  location: class DebugViews
/Users/sanogtx/WebstormProjects/EPAM_Projects/ELAT-DEV/mobile-ui-configure/node_modules/react-native-view-shot/android/src/main/java/fr/greweb/reactnativeviewshot/DebugViews.java:87: error: cannot find symbol
            @NonNull final Pair<String, View> p = stack.pop();
             ^
  symbol:   class NonNull
  location: class DebugViews
/Users/sanogtx/WebstormProjects/EPAM_Projects/ELAT-DEV/mobile-ui-configure/node_modules/react-native-view-shot/android/src/main/java/fr/greweb/reactnativeviewshot/DebugViews.java:88: error: cannot find symbol
            @NonNull final View v = p.second;

```

#### Version & Platform

```bash
react-native-view-shot@2.6.0 
```

**Platform:** Android

#### Expected behavior
Android bundle can be assembled with react-native@0.60+

#### Actual behavior
Android bundle cannot be assembled with react-native@0.60+

#### Steps to reproduce the behavior
* react-native init NewProject (create fresh react-native@0.60+ project)
* yarn add react-native-view-shot (add react-native-view-shot dependency)
* react-native run-android (run android dev build)

**Comment by oleksandr-dziuban** [comment]
@gre Hello, could you please check this issue, as this is very important to have new Android libs support for many projects... Thank you a lot

**Comment by mitrahBala** [comment]
Yes facing same issue here

**Comment by catnuxer** [comment]
@oleksandr-dziuban @mitrahBala   Hi dude, you can try yo use my pull request [https://github.com/gre/react-native-view-shot/pull/231](url)

**Comment by gre** [comment]
released a 3.0.0

**Comment by oleksandr-dziuban** [comment]
@gre @catnuxer Thank you a lot guys! You made my day!

**Comment by mitrahBala** [comment]
> released a 3.0.0

Thank you @gre  and @catnuxer . You saved my time.

**Comment by PhamMinhKha** [comment]
you can't try " yarn add react-native-view-shot@2.6.0" work for me

**Comment by lucienbl** [comment]
You can try using [that](https://github.com/mikehardy/jetifier#usage-for-source-files) to convert all the libraries to Android X (make sure you set up Android X correctly before).

**Comment by catnuxer** [comment]
@oleksandr-dziuban hi dude, please closed this issues because already solve.

**Comment by oleksandr-dziuban** [comment]
> @oleksandr-dziuban hi dude, please closed this issues because already solve.

Hello, sure, will close. Thanks for you help!

**Comment by abhi06991** [comment]
This issue still exists. Do I need to migrate to AndroidX in order for this to work?

**Comment by lucienbl** [comment]
Yes exactly, either migrate to AndroidX and jetifier or you can upgrade to RN >0.60 since that version already includes AndroidX and jetifier so you won't have much to do. So I'd suggest you to simply upgrade if it's possible.

**Comment by catnuxer** [comment]
@abhi06991 Hi dude, please try @lucienbl advice. This issue closed already, so there is no problem anymore as long you use RN 0.60.xx and update your android sdk.

Cheers

**Comment by daheeahn** [comment]
> you can try " yarn add react-native-view-shot@2.6.0" work for me

you save my day!!! thx!!
