### ISSUE TITLE
Android autolinking is not working on react-native 0.61.5

### ISSUE THREAD

**Issue by livefuture009** [gre/react-native-view-shot#282]
Hi,

I have integrated react-native-view-shot 3.1.0 in my react native project. it's working as well on iOS version. But for android, when I will build using react-native run-android, i am getting below error.

/Users/mac/Documents/Work/2020/01/Religion Tequila/7/tequila_app/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:38: error: package fr.greweb.reactnativeviewshot does not exist
import fr.greweb.reactnativeviewshot.RNViewShotPackage;
                                    ^
/Users/mac/Documents/Work/2020/01/Religion Tequila/7/tequila_app/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:98: error: cannot find symbol
      new RNViewShotPackage(),
          ^
  symbol:   class RNViewShotPackage
  location: class PackageList
2 errors

I had tried multiple times with different versions also. But same issue.. It looks like android auto linking is not working. Could you help me?

Best Regards.

**Comment by gre** [comment]
weird. our example uses 0.61.5 and works fine on Android. I'm not sure what's wrong.

**Comment by rajatgalav** [comment]
i am also facing same issue with react-native version 0.60.5

**Comment by rajatgalav** [comment]
**@livefuture009** it worked for me when i downgraded the version of library.
`npm install react-native-view-shot@~3.0.2`

**Comment by gre** [comment]
`3.1.2` has probably fixed that

**Comment by snahrvar** [comment]
Downgrading to 3.0.2 worked me (thank you @rajatgalav ). Just a quick note: 3.1.2 did not fix the Android auto-linking issue it in my case.
