### ISSUE TITLE
Not working with Android 4.4

### ISSUE THREAD

**Issue by ghostknow** [gre/react-native-view-shot#237]
java.lang.NoSuchMethodError: android.view.View.getTranslationZ

Cause the method has added after Android 5.0, any solution? Thanks

**Comment by Taym95** [comment]
We can add a condition to check the android version because `getTranslationZ` Added in API level 21, I will submit a PR.
